version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: hostel-management-app
    container_name: hostel-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - hostel-network

  webserver:
    image: nginx:alpine
    container_name: hostel-webserver
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - hostel-network

  db:
    image: mysql:8.0
    container_name: hostel-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: hostel_management
      MYSQL_ROOT_PASSWORD: railway_password
      MYSQL_PASSWORD: railway_password
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - hostel-network

volumes:
  dbdata:
    driver: local

networks:
  hostel-network:
    driver: bridge