[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile.railway"

[deploy]
startCommand = "php artisan serve --host=0.0.0.0 --port=8000"
healthcheckPath = "/"
healthcheckTimeout = 300

[[services]]
name = "web"
run = "php artisan serve --host=0.0.0.0 --port=8000"

[[services.ports]]
port = 8000
protocol = "TCP"

[env]
APP_ENV = "production"
APP_DEBUG = "false"